name: Test
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install
      - name: Unit Tests
        run: npm run test --watchAll=false
      - name: E2E Tests
        uses: cypress open --config-file=cypress.config.js
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
